### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by XeroDays** [VladVolkov22222/LightshotURLGenerator#1]
I hae windows 11 with .Net Version 8.0.* and also have .NEt SDK but somehow its not working.. when iclick it ... it opens and closses directly .

**Comment by VladOS63K** [comment]
I did this application on windows 10, net 5.0. It may not work on later versions of windows

**Comment by XeroDays** [comment]
Is it possible if you can upgrade the version?

**Comment by VladOS63K** [comment]
> Is it possible if you can upgrade the version?

Yes, but i cant upgrade to windows 11
